import { ProductCategory } from "@/interfaces";

export default {
  beverages: {
    title: "İçeceklerimiz",
    desc: "Taptaze meyve aromaları ve doğal malzemelerle hazırladığımız limonatalarımız ile hararetinizi alacak tavşan kanı çaylarımız, her yudumda ferahlığı cebinize taşırken damağınızda hafif bir mutluluk dansı yaratıyor. Bu sıcak yaz günlerinde bile içeceklerimizin serinletici keyfiyle ruhunuzu yeniden canlandırmaya hazır olun.",
    items: [
      { item: "Su", price: { fixed: 10 } },
      { item: "Çay", price: { fixed: 15 } },
      { item: "Limonata", price: { fixed: 70 } },
      { item: "Türk kahvesi", price: { fixed: 50 } },
      { item: "Beyoğlu gazoz", price: { fixed: 40 } },
      { item: "Fusetea", price: { fixed: 45 } },
      { item: "Kola", price: { fixed: 50 } },
      { item: "Fanta", price: { fixed: 50 } },
      { item: "Sprite", price: { fixed: 50 } },
    ],
  },
  deserts: {
    title: "Tatlılarımız",
    desc: "Tatlılarımız; kadife kıvamlı magnolia’dan çıtır çıtır spangle’ye, bol çikolatalı profiterolden karameli ağızda dağılan kazandibiye kadar her kaşığı gerçek bir şölen sunuyor. Her çeşidimiz, en taze malzemelerle hazırlanan ve kendine has aromasıyla damağınızda unutulmaz bir lezzet bırakıyor. Şimdi bir dilim alın ve tatlı bir düşe dalın! 😋",
    items: [
      { item: "Çilekli Magnolia", price: { fixed: 80 } },
      { item: "Oreolu Magnolia", price: { fixed: 80 } },
      { item: "Muzlu Magnolia", price: { fixed: 80 } },
      { item: "Lotus Magnolia", price: { fixed: 90 } },
      { item: "Frambuaz Magnolia", price: { fixed: 90 } },
      { item: "Antepli Magnolia", price: { fixed: 90 } },
      { item: "Dubai Magnolia", price: { fixed: 90, percentage: 11.5 } },
      { item: "Supangle", price: { fixed: 80 } },
      { item: "Çilekli Supangle", price: { fixed: 80 } },
      { item: "Profiterol", price: { fixed: 80 } },
      { item: "Sütlaç", price: { fixed: 80 } },
      { item: "Kardelen", price: { fixed: 80 } },
      { item: "Trileçe", price: { fixed: 80 } },
      { item: "Tiramisu", price: { fixed: 80 } },
      { item: "Selanik", price: { fixed: 80 } },
      { item: "Kazandibi", price: { fixed: 80 } },
      { item: "Antepli Kazandibi", price: { fixed: 100, percentage: 20 } },
      { item: "Çilek Rüyası", price: { fixed: 100 } },
      { item: "Lotus Kardelen", price: { fixed: 100, percentage: 20 } },
      { item: "Dubai Kardelen", price: { fixed: 100 } },
      { item: "Ekler", price: { fixed: 300 } },
      { item: "Spoonful", price: { fixed: 100 } },
      { item: "Sütlü Kadayıf", price: { fixed: 60 } },
      { item: "Tahinli Kadayıf", price: { fixed: 80, percentage: 12 } },
    ],
  },
} satisfies ProductCategory;
