import { ProductCategory } from "@/interfaces";

export default {
  beverages: {
    title: "İçeceklerimiz",
    desc: "Taptaze meyve aromaları ve doğal malzemelerle hazırladığımız limonatalarımız, hararetinizi evinizden alacak tavşan kanı çaylarımızla her yudum ferahlığı cebinize taşırken, damağınızda hafif bir mutluluk dansı yaratıyor bu sıcak yaz günlerinde bile serinletici keyfi ve canlı hissettireniyle ruhunuzu canlandırmaya hazır olun!",
    items: [
      { item: "Su", price: { fixed: 10 } },
      { item: "Çay", price: { fixed: 15 } },
      { item: "Limonata", price: { fixed: 70 } },
      { item: "Türk kahvesi", price: { fixed: 50 } },
      { item: "Beyoğlu gazoz", price: { fixed: 40 } },
      { item: "Fusetea", price: { fixed: 45 } },
      { item: "Kola", price: { fixed: 50 } },
      { item: "Fanta", price: { fixed: 50 } },
      { item: "Sprite", price: { fixed: 50 } },
    ],
  },
  deserts: {
    title: "Tatlılarımız",
    desc: "Tatlılarımız, kadife kıvamlı magnolia'dan çıtır çıtır spangle'ye, bol çikolatalı profiterolden karameli ağızda dağılan kazandibiye kadar her kaşığı gerçek bir şölen sunuyor, en taze malzemelerle hazırlanan her çeşidimiz, kendine has aromasıyla damağınızda unutulmaz bir lezzet bırakıyor! Şimdi bir dilim alın ve tatlı bir düşe dalın 😋.",
    items: [
      { item: "Çikolatalı Magnolia", price: { fixed: 80, percentage: 12 } },
      { item: "Oreolu Magnolia", price: { fixed: 80 } },
      { item: "Muzlu Magnolia", price: { fixed: 80 } },
      { item: "Lotus Magnolia", price: { fixed: 90 } },
      { item: "Framboaz Magnolia", price: { fixed: 90 } },
      { item: "Antepli Magnolia", price: { fixed: 90 } },
      { item: "Dubaili Magnolia", price: { fixed: 90 } },
      { item: "Spangle", price: { fixed: 80 } },
      { item: "Çilekli Spangle", price: { fixed: 80 } },
      { item: "Profiterol", price: { fixed: 80 } },
      { item: "Sütlaç", price: { fixed: 80 } },
      { item: "Kardelen", price: { fixed: 80 } },
      { item: "Trileçe", price: { fixed: 80 } },
      { item: "Tiramisu", price: { fixed: 80 } },
      { item: "Şelanik", price: { fixed: 80 } },
      { item: "Kazandibi", price: { fixed: 80 } },
      { item: "Antepli Kazandibi", price: { fixed: 100, percentage: 20 } },
      { item: "Çilek Rüyası", price: { fixed: 100 } },
      { item: "Lotus Kardelen", price: { fixed: 100, percentage: 20 } },
      { item: "Dubar Kardelen", price: { fixed: 100 } },
      { item: "Ekler", price: { fixed: 300 } },
      { item: "Spanfoul", price: { fixed: 100 } },
      { item: "Sütlü Kadayıf", price: { fixed: 60 } },
      { item: "Tahinli Kadayıf", price: { fixed: 80 } },
    ],
  },
} satisfies ProductCategory;
